---
# Setup infrastructure and application for local development environment

- name: setup local development nodes
  hosts: project--£PROJECT-LOWER-CASE:&env--dev-local
  remote_user: "{{ privileged_remote_user }}"
  become: yes
  roles:
    - bas-ansible-roles-collection.system-core
