---
# Setup infrastructure and application for development environment

- name: setup development nodes and apply web and application team conventions
  hosts: project--£PROJECT:&env--dev-local
  remote_user: "{{ privileged_remote_user }}"
  become: yes
  roles:
    - bas-ansible-roles-collection.system-core
    - antarctica.bas-web-applications-team
