---
# Setup infrastructure and application for development environment

- name: setup development nodes and configure to follow BAS conventions
  hosts: project--£PROJECT-LOWER-CASE:&env--dev-local
  remote_user: "{{ privileged_remote_user }}"
  become: yes
  roles:
    - bas-ansible-roles-collection.system-core
    - antarctica.bas-motd
